SECRET_KEY = "vCB9e87YPHkd1_"
MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = "Ce6656yXV6qZqyM7"
MYSQL_DATABASE = "flask_db_app"

DATABASE_CONNECTION_URI= f'mysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}'